### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by idontgetoutmuch** [terranpro/magit-gerrit#14]
Compiling file /Users/dom/.emacs.d/elpa/magit-gerrit-20141117.1704/magit-gerrit-pkg.el at Wed Jan  7 19:12:55 2015
Entering directory `/Users/dom/.emacs.d/elpa/magit-gerrit-20141117.1704/'

Compiling file /Users/dom/.emacs.d/elpa/magit-gerrit-20141117.1704/magit-gerrit.el at Wed Jan  7 19:12:56 2015
magit-gerrit.el:197:1:Error: Incompatible place needs recompilation: magit-section-hidden

**Comment by mnuessler** [comment]
It works for me. When I install magit-gerrit from MELPA, it installs the latest magit package as a dependency also from MELPA. Maybe you are are using a different version of magit? Can you please check your magit version (`M-x magit-version`)?

**Comment by idontgetoutmuch** [comment]
magit-20140129.1145 perhaps I should uninstall magit and then install magit-gerrit?

**Comment by idontgetoutmuch** [comment]
Ok that seems to have fixed it but I thought that the install of the latest magit should have been automatic.
