### ISSUE TITLE
Missing "Reviews" section in magit status

### ISSUE THREAD

**Issue by ionrock** [terranpro/magit-gerrit#15]
I have a feeling I'm simply missing something. I don't see any reviews for a specific repo even though I've set it up with gerrit / git review. I've tried pulling from the gerrit repo but that doesn't list any reviews. 

To be clear, I'm still in the master branch.

**Comment by mnuessler** [comment]
Does the URL of your remote contain the SSH scheme and the default Gerrit port (i. e. ssh://user@my.gerrit.host.de:29418/my-project)? If not you might have to set 'magit-gerrit-ssh-creds'.

**Comment by ionrock** [comment]
Ah OK. So I have the Reviews field now, but no reviews.

**Comment by ionrock** [comment]
OK! The issue was I needed to specify the repo as `ssh://user@gerrithost.net:port/path/project`. I had a .git at the end. Removing that and making sure I didn't add the `magit-gerrit-ssh-creds` did the trick. 

Closing this one. Thanks @mnuessler!
