### ISSUE TITLE
Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [terranpro/magit-gerrit#16]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by terranpro** [comment]
Hi,

I added a version tag "v0.1" - is this enough for it to work with melpa stable?

Regards,
Brian

**Comment by nlamirault** [comment]
I think. Thanks

**Comment by terranpro** [comment]
Great, will go ahead and close this then.
