### ISSUE TITLE
keystroke help

### ISSUE THREAD

**Issue by hexmode** [terranpro/magit-gerrit#17]
magit provides a nifty menu'd interface for keystrokes that lets you discover how to do what you want, but magit-gerrit doesn't appear to have any keystrokes assigned or a way to integrate them.

Please add support for the keystroke menu.

**Comment by hexmode** [comment]
Posted request for help upstream here: https://groups.google.com/d/msg/magit/WM7ge05L_Nw/uOFuTpkhaoIJ

**Comment by terranpro** [comment]
Hello,

Which version of magit are you using?  I have a feeling you're on their bleeding-edge `next` branch.

Is the menu interface you refer to triggered by `h` from a `magit-status` buffer?  I'm just now checking out their new stuff.  Apparently I need to *git* with the times, as my system git version is now behind magit's required as well.

Bad puns aside, I'll try to make the necessary updates and then create a matching `next` branch for magit-gerrit.

Thanks for the ping!
Brian

**Comment by hexmode** [comment]
I'm using 20150422.316, installed from ELPA, so I suppose this is the
bleeding edge.

Thanks for the response!

**Comment by terranpro** [comment]
Well, there's now a corresponding `next` branch in magit-gerrit that makes things work with magit's `next` branch's API changes and their new popup menu.  Maybe you could check if that fixes your issue?

After opening magit help popup with `h` the gerrit popup should be there with keystroke `R`.  Commit 53b30ab4be0ac595c9226dacd4ec2216af7813be

I've yet to use Emacs package management capabilities so I'm not exactly sure how things work, but looking around MELPA it seems like the magit recipe is tied to magit's `master` branch.  If so, then I may have solved a future compatibility problem but not your actual issue!  

Is there a way to find the git commit id/sha used when building your magit package?  BTW, in `master`, the gerrit menu could be opened with `T` from a magit status buffer.

Hope this helps!

**Comment by hexmode** [comment]
I missed the T keystroke (I should read the docs, ya know?), but it doesn't show up when you hit ? in a magit buffer after magit-gerrit is activated.

elpa installs magit into ~/.emacs.d/elpa/magit-20150424.1706 so I assume that it is using the master branch.  You can configure elpa to point to the bleeding edge stuff, but I don't think I have.

I'm installing [magit](http://melpa.org/#/magit) (and [magit-gerrit](http://melpa.org/#/magit-gerrit)) from melpa and, from there you can see what branches melpa's recipes are pointing to ([master](https://github.com/milkypostman/melpa/blob/master/recipes/magit)).

**Comment by terranpro** [comment]
Ok great so magit-gerrit should be working but it's just missing from this key-mode menu.
This is the first time I've run across the `?` hotkey!  It looks like we can add it to the `dispatch` key-mode-popup:

`(magit-key-mode-insert-action 'dispatch (kbd "T") "Gerrit" 'magit-key-mode-popup-gerrit)`

Worked locally for me - could you check if this is what you were looking for?

Had to settle for `T` in the status buffer because `G` was taken for `magit-refresh-all`, but looks like both `G` and `T` are available in this dispatch popup.  Anyways, Cheers!

**Comment by hexmode** [comment]
terranpro writes:

> `(magit-key-mode-insert-action 'dispatch (kbd "T") "Gerrit" 'magit-key-mode-popup-gerrit)`
>
> Worked locally for me - could you check if this is what you were looking for?

Works for me.  Had to load magit-gerrit to make the keystroke work.
