### ISSUE TITLE
void-function magit-cmd-insert-section

### ISSUE THREAD

**Issue by louxiu** [terranpro/magit-gerrit#18]
when i `magit-status`, error void-function magit-cmd-insert-section occur. Where is this function defined? I checked the magit, nothing lucky.

**Comment by terranpro** [comment]
Hi,

What version of magit are you using?  In my magit I see it defined in `magit.el`

    (defmacro magit-cmd-insert-section (arglist washer program &rest args)
      "\n\n(fn (TYPE &optional HEADING) WASHER PROGRAM &rest ARGS)"
    ...

I'm on their latest origin/master:

https://github.com/magit/magit/commit/40f33c9b8a0cd5ac39fdcca525dd734e7e79e1af

**Comment by louxiu** [comment]
hi, terranpro. Sorry for late reply. I follow the instruction of https://github.com/magit/magit and use `next` branch. I noticed that commit 40f33c9b8a0cd5ac39fdcca525dd734e7e79e1af(commit at Apr 24) is not the latest one. Both in `next` and master branch, I see no  magit-cmd-insert-section defined. It seems that they replace it with magit-git-wash in commit 214aafabffabb86203ac1bb74ecb56d13dee9cf9.

**Comment by terranpro** [comment]
Hi louxiu, yes, their `next` branch has undergone extensive changes.

As such, I created a matching `next` branch in magit-gerrit; could you give this branch a try?  I'm trying to keep it updated to their latest changes.

**Comment by louxiu** [comment]
Thanks, terranpro. The error has gone away.

**Comment by terranpro** [comment]
Great, thanks!
