### ISSUE TITLE
magit-diff-buffer-name has been removed in magit master

### ISSUE THREAD

**Issue by louxiu** [terranpro/magit-gerrit#20]
(defvar magit-diff-buffer-name "*magit-diff*"
  "Name of buffer used to display a diff.")

The above line has been removed in magit. So  when use `magit-gerrit-view-patchset-diff`, error will occur.

**Comment by terranpro** [comment]
Hi,

I think this has been fixed in both `master` and `next`.
I don't see `magit-diff-buffer-name` in use anymore.
Could you check this again?

Thanks,
Brian

**Comment by louxiu** [comment]
Hi, terranpro
I checked the master branch, `magit-diff-buffer-name` has been removed from `magit-gerrit-view-patchset-diff`. but in next branch, it is still there. `(buf (get-buffer-create magit-diff-buffer-name))`. though the `buf` variable is unused.

**Comment by terranpro** [comment]
Whoops, you are right - the change was sitting in my local branch.

Fixed here: 9cb8855cc6a41d496a860b8de714022879c9b0e8

Thanks for the report!

**Comment by louxiu** [comment]
Thanks, the problem is fixed.
