### ISSUE TITLE
R key prefix conflicts with magit-file-rename

### ISSUE THREAD

**Issue by aspiers** [terranpro/magit-gerrit#31]
At least in newer versions of magit, `R` is already bound to `magit-file-rename`, so this prefix needs a better binding, or at very least for it to be configurable.

**Comment by terranpro** [comment]
Hi,

Thanks for the heads-up - didn't know we were masking git rename, but it seems most of the a-zA-Z are already taken by magit!  

Thought about going for a default \` or `~` but maybe there's a better option?

**Comment by terranpro** [comment]
My fix missed a spot that was corrected by PR #39
Will go ahead and close now, please reopen and/or add any extra feedback! Thanks!
