### ISSUE TITLE
magit-fetch-current undefined

### ISSUE THREAD

**Issue by narayandesai** [terranpro/magit-gerrit#33]
Using magit and magit-gerrit from elpa (magit 20160105.1035, git 2.7.0, and Emacs 24.5.6, magit-gerrit is 20151202.1618), when submitting a review, I get the error:

(from *Messages*)
Detected magit-gerrit-ssh-creds=XXX@XXX
Type C-h i to view popup manual, ? to describe an argument or action.
magit-gerrit-submit-review: Symbol's function definition is void: magit-fetch-current

From a cursory check, it appears that magit-fetch-current has disappeared from the upstream magit.

The review was properly submitted, but origin hadn't been updated.

This is an awesome mode, and has ground off a lot of the rough edges in my use of gerrit, magit and emacs. Thanks!

**Comment by louxiu** [comment]
`magit-fetch-current` has been remove from recent magit. I make a patch to  fIx it https://github.com/terranpro/magit-gerrit/pull/34

**Comment by terranpro** [comment]
Thanks for the report (and the kind words!) and thanks for the patch louxiu!
