### ISSUE TITLE
magit-process-wait has disappeared

### ISSUE THREAD

**Issue by narayandesai** [terranpro/magit-gerrit#40]
It seems that magit-process-wait isn't available in magit any more. Applying a fix similar to this: 
https://github.com/magit/magit-annex/commit/db655ed50f38af8940e808afc30447746e2c648a

in the tree (in both locations) fixes the problem.

**Comment by kozhukalov** [comment]
I'm experiencing the same issue. I defined magit-process-wait function in my .emacs.

**Comment by terranpro** [comment]
Hi guys, Looks like this issue has been fixed by PR #37 
Thanks for the report and info!
